In [3]:
import pandas as pd

In [4]:
train_df = pd.read_csv(r'D:\Codes\Artificial_Intelligence\Machine_Learning\Scikit_Learn\Projects\Datasets\flood_prediction_orginal\train.csv')

In [5]:
train_df.columns

Index(['id', 'MonsoonIntensity', 'TopographyDrainage', 'RiverManagement',
       'Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality',
       'Siltation', 'AgriculturalPractices', 'Encroachments',
       'IneffectiveDisasterPreparedness', 'DrainageSystems',
       'CoastalVulnerability', 'Landslides', 'Watersheds',
       'DeterioratingInfrastructure', 'PopulationScore', 'WetlandLoss',
       'InadequatePlanning', 'PoliticalFactors', 'FloodProbability'],
      dtype='object')

In [6]:
train_df.head()

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,0,5,8,5,8,6,4,4,3,3,...,5,3,3,5,4,7,5,7,3,0.445
1,1,6,7,4,4,8,8,3,5,4,...,7,2,0,3,5,3,3,4,3,0.450
2,2,6,5,6,7,3,7,1,5,4,...,7,3,7,5,6,8,2,3,3,0.530
3,3,3,4,6,5,4,8,4,7,6,...,2,4,7,4,4,6,5,7,5,0.535
4,4,5,3,2,6,4,4,3,3,3,...,2,2,6,6,4,1,2,3,5,0.415

In [7]:
train_df_deep = pd.read_csv(r'D:\Codes\Artificial_Intelligence\Machine_Learning\Scikit_Learn\Projects\Codes\submission_stacking.csv')

In [8]:
train_df_deep.head()

        id  FloodProbability
0  1117957          0.474274
1  1117958          0.472255
2  1117959          0.494960
3  1117960          0.527776
4  1117961          0.344955

In [9]:
print(train_df.shape)
print(train_df_deep.shape)

(1117957, 22)
(745305, 2)